CREATE TABLE IF NOT EXISTS public.n8n_supabase_test (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo INTEGER NOT NULL,
  nome TEXT,
  valor NUMERIC(14,2),
  atualizado_em TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT n8n_supabase_test_codigo_unique UNIQUE (codigo)
);
SELECT * FROM public.n8n_supabase_test ORDER BY id;
