import type { IExecuteFunctions, INodeExecutionData, INodeType, INodeTypeDescription } from 'n8n-workflow';

type Op='select'|'insert'|'upsert'|'update'|'delete'|'count'|'rpc';
const url=(s:string)=>s.replace(/\/+$/,'');
const json=(s:string,l:string)=>{try{return JSON.parse(s)}catch{throw new Error(`${l} contém JSON inválido.`)}};
export class SupabaseAdvanced implements INodeType {
 description: INodeTypeDescription={displayName:'Supabase Advanced',name:'supabaseAdvanced',icon:'file:supabase.svg',group:['transform'],version:1,subtitle:'={{$parameter["operation"]}}',description:'Advanced Supabase/PostgREST operations for n8n.',defaults:{name:'Supabase Advanced'},inputs:['main'],outputs:['main'],credentials:[{name:'supabaseAdvancedApi',required:true}],properties:[
 {displayName:'Operation',name:'operation',type:'options',options:[{name:'Select',value:'select'},{name:'Insert',value:'insert'},{name:'Upsert',value:'upsert'},{name:'Update',value:'update'},{name:'Delete',value:'delete'},{name:'Count',value:'count'},{name:'RPC',value:'rpc'}],default:'select'},
 {displayName:'Table',name:'table',type:'string',default:'',required:true,displayOptions:{show:{operation:['select','insert','upsert','update','delete','count']}}},
 {displayName:'Columns',name:'columns',type:'string',default:'*',displayOptions:{show:{operation:['select']}}},
 {displayName:'Return All',name:'returnAll',type:'boolean',default:false,displayOptions:{show:{operation:['select']}}},
 {displayName:'Limit',name:'limit',type:'number',default:100,displayOptions:{show:{operation:['select']}}},
 {displayName:'Offset',name:'offset',type:'number',default:0,displayOptions:{show:{operation:['select']}}},
 {displayName:'Order By',name:'orderBy',type:'string',default:'',placeholder:'created_at.desc',displayOptions:{show:{operation:['select']}}},
 {displayName:'Filters',name:'filters',type:'fixedCollection',typeOptions:{multipleValues:true},default:{},displayOptions:{show:{operation:['select','update','delete','count']}},options:[{displayName:'Filter',name:'filter',values:[{displayName:'Field',name:'field',type:'string',default:'',required:true},{displayName:'Operator',name:'operator',type:'options',options:[{name:'Equal',value:'eq'},{name:'Not Equal',value:'neq'},{name:'Greater Than',value:'gt'},{name:'Greater Than or Equal',value:'gte'},{name:'Less Than',value:'lt'},{name:'Less Than or Equal',value:'lte'},{name:'Like',value:'like'},{name:'ILike',value:'ilike'},{name:'Is',value:'is'},{name:'In',value:'in'},{name:'Not',value:'not'}],default:'eq'},{displayName:'Value',name:'value',type:'string',default:''}]}]},
 {displayName:'Data Source',name:'dataSource',type:'options',options:[{name:'JSON',value:'json'},{name:'Input Items',value:'inputItems'}],default:'json',displayOptions:{show:{operation:['insert','upsert','update']}}},
 {displayName:'JSON Data',name:'jsonData',type:'json',default:'{\n  "codigo": 1001,\n  "nome": "Produto Teste"\n}',displayOptions:{show:{operation:['insert','upsert','update'],dataSource:['json']}}},
 {displayName:'Conflict Columns',name:'onConflict',type:'string',default:'',placeholder:'filial,numero,serie',displayOptions:{show:{operation:['upsert']}}},
 {displayName:'Ignore Duplicates',name:'ignoreDuplicates',type:'boolean',default:false,displayOptions:{show:{operation:['upsert']}}},
 {displayName:'Return Data',name:'returnData',type:'boolean',default:true,displayOptions:{show:{operation:['insert','upsert','update','delete']}}},
 {displayName:'Function Name',name:'functionName',type:'string',default:'',required:true,displayOptions:{show:{operation:['rpc']}}},
 {displayName:'Arguments',name:'rpcArguments',type:'json',default:'{}',displayOptions:{show:{operation:['rpc']}}}
 ]};
 async execute(this:IExecuteFunctions):Promise<INodeExecutionData[][]>{
  const items=this.getInputData(), op=this.getNodeParameter('operation',0) as Op, c=await this.getCredentials('supabaseAdvancedApi');
  const base=`${url(String(c.supabaseUrl))}/rest/v1`, key=String(c.apiKey); if(!base||!key) throw new Error('Supabase URL e API Key são obrigatórios.');
  const headers:Record<string,string>={apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json'}; const out:INodeExecutionData[]=[];
  const filters=(i:number)=>{const raw=this.getNodeParameter('filters',i,{}) as {filter?:Array<{field:string;operator:string;value:string}>}; const q:Record<string,string>={}; for(const f of raw?.filter??[]) if(f.field) q[f.field]=`${f.operator}.${String(f.value??'').trim()}`; return q};
  const req=async(method:'GET'|'POST'|'PATCH'|'DELETE',u:string,body?:unknown,qs?:Record<string,string>,extra?:Record<string,string>)=>{try{return await this.helpers.httpRequest({method,url:u,headers:{...headers,...extra,...(method!=='GET'?{'Content-Type':'application/json'}:{})},qs,body,json:true})}catch(e){const x=e as any,b=x?.response?.body;if(b) throw new Error(`Supabase${b.code?` [${b.code}]`:''}: ${b.message??'Erro na API'}${b.details?` Detalhes: ${b.details}`:''}${b.hint?` Sugestão: ${b.hint}`:''}`);throw e}};
  if(op==='rpc'){const fn=String(this.getNodeParameter('functionName',0));const r=await req('POST',`${base}/rpc/${encodeURIComponent(fn)}`,json(String(this.getNodeParameter('rpcArguments',0)),'Arguments'));for(const x of (Array.isArray(r)?r:[r])) out.push({json:x as any});return[out]}
  const table=String(this.getNodeParameter('table',0)), u=`${base}/${encodeURIComponent(table)}`;
  if(op==='select'){const all=this.getNodeParameter('returnAll',0) as boolean, lim=Math.max(1,Number(this.getNodeParameter('limit',0))), off=Math.max(0,Number(this.getNodeParameter('offset',0))), cols=String(this.getNodeParameter('columns',0)||'*'), order=String(this.getNodeParameter('orderBy',0)||''); let pos=off; do{const r=await req('GET',u,undefined,{select:cols,...filters(0),...(order?{order}:{}),limit:String(lim),offset:String(pos)});const rows=Array.isArray(r)?r:[];for(const x of rows)out.push({json:x as any});if(!all||rows.length<lim)break;pos+=lim}while(true);return[out]}
  if(op==='count'){const r=await req('GET',u,undefined,{select:'id',...filters(0),limit:'1'},{Prefer:'count=exact'});out.push({json:{count:Array.isArray(r)?r.length:0}});return[out]}
  if(op==='insert'||op==='upsert'){const src=String(this.getNodeParameter('dataSource',0));const payload=src==='inputItems'?items.map(x=>x.json):json(String(this.getNodeParameter('jsonData',0)),'JSON Data');const ret=this.getNodeParameter('returnData',0) as boolean;const extra:Record<string,string>={Prefer:ret?'return=representation':'return=minimal'};const qs:Record<string,string>={};if(op==='upsert'){const conflict=String(this.getNodeParameter('onConflict',0)||'');const ignore=this.getNodeParameter('ignoreDuplicates',0) as boolean;if(conflict)qs.on_conflict=conflict;extra.Prefer+=ignore?',resolution=ignore-duplicates':',resolution=merge-duplicates'}const r=await req('POST',u,payload,qs,extra);if(ret){for(const x of(Array.isArray(r)?r:[r]))out.push({json:x as any})}else out.push({json:{success:true,operation:op}});return[out]}
  if(op==='update'||op==='delete'){const f=filters(0);if(!Object.keys(f).length)throw new Error(`${op.toUpperCase()} exige pelo menos um filtro por segurança.`);const ret=this.getNodeParameter('returnData',0) as boolean;if(op==='update'){const src=String(this.getNodeParameter('dataSource',0));const payload=src==='inputItems'?(items[0]?.json??{}):json(String(this.getNodeParameter('jsonData',0)),'JSON Data');const r=await req('PATCH',u,payload,f,{Prefer:ret?'return=representation':'return=minimal'});if(ret)for(const x of(Array.isArray(r)?r:[r]))out.push({json:x as any});else out.push({json:{success:true,operation:op}})}else{const r=await req('DELETE',u,undefined,f,{Prefer:ret?'return=representation':'return=minimal'});if(ret)for(const x of(Array.isArray(r)?r:[r]))out.push({json:x as any});else out.push({json:{success:true,operation:op}})}return[out]}
  throw new Error(`Operação não suportada: ${op}`);
 }
}
